src/Form.jsx

Form (validation): Reset "validSync" and "validAsync" on field change

---

src/utils/fieldUtils/validateAsync.js

We will get them all eventually :D

Async validate now returns mutable JS object

---

package-lock.json
package.json
src/Form.jsx
stories/DefaultForm.js

Form: Introduce "onInvalid" callback method

---

.circleci/config.yml

CI: Add CircleCI config

---

package-lock.json
package.json
src/Form.jsx
src/utils/fieldUtils/getErrorMessage.js
src/utils/fieldUtils/validate.js
src/utils/fieldUtils/validateAsync.js
src/utils/fieldUtils/validateSync.js
stories/DefaultForm.js

Form: Provide "form" instead of "formProps" in various callbacks

---

src/Fields/Checkbox.jsx
src/Fields/Field.jsx
src/Fields/Input.jsx
src/Fields/Radio.jsx
src/Fields/Select.jsx
src/Fields/Textarea.jsx
src/Fields/index.jsx
stories/DefaultForm.js
stories/templates/MyTextarea.js

Feature: "Field.Textarea"

---

src/Condition.jsx
src/utils/fieldUtils/serializeFields.js
stories/Conditional.js

fieldUtils (serializeFields): Accept custom "valueResolver" function

---

test/unit/components/connectField.spec.js
test/unit/components/index.js

Test: Add tests for "connectField"

---

src/Fields/Field.jsx
stories/DefaultForm.jsx

Implements an uncaught bug that `placeholder` prop is not passed to the Field.

Field: Propagate "placeholder" prop to Field Component

---

src/Form.jsx

Form: Bypass events coming from unregistered fields

---

docs/SUMMARY.md
docs/callbacks/Field/onBlur.md
docs/callbacks/Field/onChange.md
docs/callbacks/Field/onFocus.md
docs/callbacks/Form/onInvalid.md
docs/callbacks/Form/onReset.md
docs/callbacks/Form/onSubmitEnd.md
docs/callbacks/Form/onSubmitStart.md
docs/callbacks/Form/onSubmitted.md
docs/methods/Form/reset.md
src/Form.jsx
test/unit/components/Form.spec.js

Form: Add "onReset" callback method

---

package-lock.json
package.json
src/Form.jsx
stories/BugWithForm.jsx

Form (validateField): Get error message when form has messages

---

src/Form.jsx

Implements #91.
This is a minor change, it can be merged and then tested on the production projects. I can provide the testing after the holidays end.

Form (handleFieldBlur): Do not mutate "disabled" by default

---

src/components/Form.jsx
src/components/createField.jsx
src/utils/IterableInstance.js
src/utils/fieldUtils/getErrorMessages.js
test/common/defer.js

Form: Throw when dispatched "action" does not return a Promise

---

src/components/Form.jsx
stories/ValidationExample.jsx
test/unit/components/Form.spec.js

Form: Introduce "innerRef" to reference <form> element

---

src/components/Form.jsx
src/components/createField.jsx
src/utils/fieldUtils/validateSync.js
stories/ControlledForm.jsx
test/unit/utils/getErrorMessages.spec.js
test/unit/utils/validateSync/mixed.spec.js
test/unit/utils/validateSync/name.spec.js
test/unit/utils/validateSync/type.spec.js

Field: Properly update and validate the controlled value updates

---

src/components/createField.jsx
src/utils/fieldUtils/serializeFields.js
test/unit/utils/index.spec.js
test/unit/utils/serializeFields.spec.js

createField: Introduce "skip" prop to bypass field validation

---

cypress/components/Checkbox.jsx
cypress/components/Input.jsx
cypress/components/Radio.jsx
cypress/components/Select.jsx
cypress/components/Textarea.jsx
cypress/components/index.js
cypress/integration/basics/Interactions.spec.jsx
cypress/integration/basics/index.js
cypress/integration/index.js
cypress/scenarios/Basics/Interactions.controlled.jsx
cypress/scenarios/Basics/Interactions.jsx

Contributes to #165.
* Adds integration tests for basic fields interactions for controlled and uncontrolled fields

Adds integration tests for basic fields interactions

---

src/components/Form.jsx
src/components/FormProvider.jsx
test/unit/components/Form.spec.js

Form: Use a fallback value for "this.context.debounceTime"

---

docs/getting-started/creating-fields.md
docs/hoc/createField/presets.md
examples/fields/Input.jsx
examples/fields/Textarea.jsx
src/fieldPresets/index.js
src/fieldPresets/input.js
src/fieldPresets/radio.js
src/fieldPresets/select.js
src/fieldPresets/textarea.js

fieldPresets: Map essential attributes using "enforceProps"

---

docs/hoc/createField/options.md
src/components/Form.jsx
src/components/createField.jsx
src/fieldPresets/checkbox.js
stories/RxProps.jsx
test/unit/components/Field.spec.js

Introduce "CreateFieldOptions.shouldValidateOnMount"

---

docs/validation/messages.md
src/utils/fieldUtils/validate.js
stories/GroupedFields.jsx
stories/ValidationExample.jsx

Messages: Uses "rule" key instead of "rules" for named messages

---

examples/full-examples/RegistrationForm/RegistrationForm.jsx
examples/full-examples/RegistrationForm/index.jsx
examples/full-examples/RegistrationForm/validation-messages.js
examples/full-examples/RegistrationForm/validation-rules.js
examples/index.js
package-lock.json
package.json
src/components/Form.jsx
src/utils/flattenDeep.js

Form (validate): Provides default "predicate" function as a argument

---

src/components/Form.jsx
src/components/createField.jsx

221 field debounce validate missing

---

README.md
cypress/integration/basics/Interactions.controlled.spec.jsx
cypress/integration/field-grouping/NestedGroups.spec.jsx
cypress/integration/field-grouping/SimpleGroup.spec.jsx
cypress/integration/field-grouping/SplitGroups.spec.jsx
cypress/integration/field-grouping/index.js
cypress/integration/index.js
docs/components/Field.Group.md
examples/field-grouping/NestedGroups.jsx
examples/field-grouping/SimpleGroup.jsx
examples/field-grouping/SplitGroups.jsx
examples/fields/Input.jsx
examples/index.js
src/components/Field/Field.Group.jsx
src/components/createField.jsx

Field.Group: Adds support for nested field groups

---

package-lock.json
package.json
src/components/Form.jsx
src/utils/fieldUtils/getValidityState.js
test/unit/utils/fieldUtils/index.spec.js

213 checkbox valid not set

---

.storybook/webpack.config.js
cypress/plugins/index.js
examples/fields/Checkbox.jsx
examples/fields/Input.jsx
examples/fields/Radio.jsx
examples/fields/Select.jsx
examples/fields/Textarea.jsx
index.js
package.json
test/index.spec.js
test/unit/components/Field.Group.spec.js
test/unit/components/Field.spec.js
test/unit/components/Form.spec.js
test/unit/components/FormProvider.spec.js
webpack.config.js

214 environment build

---

src/utils/fieldUtils/validateAsync.js
src/utils/fieldUtils/validateSync.js
test/unit/utils/fieldUtils/validateSync/mixed.spec.js
test/unit/utils/fieldUtils/validateSync/name.spec.js
test/unit/utils/fieldUtils/validateSync/type.spec.js

Use "valuePropName" prop instead of hard "value" in resolvers

---

docs/hoc/createField/options.md
examples/fields/Checkbox.jsx
src/components/createField.jsx
src/fieldPresets/checkbox.js
src/fieldPresets/input.js
src/fieldPresets/select.js
src/fieldPresets/textarea.js

createField: Adds "initialValue" option

---

README.md
docs/hoc/createField/props.md
src/components/Form.jsx
src/components/createField.jsx
src/utils/fieldUtils/resetField.js
src/utils/fieldUtils/validate.js

Adds "validated" field prop

---

cypress/integration/basics/Interactions.controlled.spec.jsx
cypress/integration/basics/Interactions.uncontrolled.spec.jsx
cypress/integration/components/FormProvider.spec.jsx
cypress/integration/reactive-props/index.spec.jsx
cypress/integration/validation/AsyncValidation/index.spec.jsx
cypress/integration/validation/SyncValidation/Field.props.rule.spec.jsx
cypress/integration/validation/SyncValidation/Form.props.rules.spec.jsx
examples/reactive-props/Field.props.rule.jsx
examples/validation/SyncValidation/Field.props.rule.jsx
src/components/Form.jsx
src/utils/fieldUtils/createPropGetter.js
src/utils/fieldUtils/validateSync.js
src/utils/flattenDeep.js
src/utils/formUtils/getFieldRules.js
src/utils/formUtils/index.js
src/utils/formUtils/mergeRules.js
src/utils/rxUtils/addPropsObserver.js
src/utils/rxUtils/createRulesSubscriptions.js
src/utils/rxUtils/makeObservable.js
test/unit/utils/fieldUtils/serializeFields.spec.js
test/unit/utils/fieldUtils/validateSync/mixed.spec.js
test/unit/utils/fieldUtils/validateSync/name.spec.js
test/unit/utils/fieldUtils/validateSync/type.spec.js

Adds reactive behavior to "Field.props.rule"

---

src/components/Form.jsx
src/components/createField.jsx
src/utils/fieldUtils/validate.js
src/utils/rxUtils/createSubscriptions.js

Removes development logging from the build

---

src/components/Form.jsx

Supports custom predicate function for "clear" and "reset" form methods

---

README.md
cypress/support/commands.js
src/components/Form.jsx

* Closes #292
**Release version:** `1.5.1`

Form: Propagates "style" prop

---

examples/fields/FileInput.jsx
examples/fields/index.js

Adds "FileInput" example

---

src/components/Form.jsx
src/utils/fieldUtils/flattenFields.js

Removes deprecated usage of "deleteIn" method

---

cypress/integration/custom-fields/BirthDate.spec.js
examples/custom-fields/BirthDate.jsx
examples/fields/BirthDate.jsx
src/components/createField.jsx

* Closes #319 
Please see the spec in the ticket's description.

Use "assertValue" as the default value for "shouldValidateOnMount"

---

.circleci/config.yml
.npmignore
.storybook/webpack.config.js
index.js
package-lock.json
package.json
webpack.config.js

Omits minification during the bundle build

---

cypress/integration/basics/FieldUnmounting.spec.js
cypress/integration/basics/index.js
examples/basics/FieldUnmounting.jsx
examples/index.js
src/components/Form.jsx

Form: Supports multiple unmounting fields

---

src/components/Form.jsx

* Covers #333, but requires tests

Form.clear: Does not rejects fields that do not match predicate

---

cypress/integration/basics/DebouncedChange.spec.js
cypress/integration/basics/Submit.spec.js
cypress/integration/basics/index.js
examples/basics/DebouncedChange.jsx
examples/full/RegistrationForm/RegistrationForm.jsx
examples/index.js
src/components/Form.jsx
src/utils/handlers/handleFieldChange.js

Dispatches "onChange" callback on "Form.updateFieldsWith()"

---

cypress/integration/basics/Clear.spec.js
examples/basics/Clear.jsx
examples/index.js

Adds integration test for "form.clear()"

---

src/components/Form.jsx
src/utils/handlers/validateField.js

Sets "expected" to "true" for fields that didn't require validation

---

cypress/integration/behavior/Pristine.spec.js
cypress/integration/behavior/index.js
cypress/support/commands.js
examples/basics/Pristine.jsx
examples/fields/Checkbox.jsx
examples/fields/Input.jsx
examples/fields/Radio.jsx
examples/fields/Textarea.jsx
examples/index.js
src/utils/handlers/handleFieldChange.js
src/utils/recordUtils.js
src/utils/recordUtils.test.js

Adds support for "pristine" in field state

---

src/utils/handlers/handleFieldChange.js

handleFieldChange: Dispatches the handler first, returns later

---

cypress/integration/validation/other/ConditionalSchema.spec.js
examples/components/FormProvider/PropUpdates.jsx
examples/index.js
examples/validation/other/ConditionalSchema.jsx
package-lock.json
src/components/Form.jsx
src/utils/formUtils/mergeRules.js
src/utils/handlers/validateField.js
src/utils/validation/reflectors/reflectValidationResult.js
src/utils/validation/validateSync/index.js
src/utils/validation/validateSync/shouldValidateSync.js

- Fixes #362 
Also changes `shouldValidateSync` predicates to include `fieldProps.validSync`. This will validated previously validated fields (which is not expected), but quickfix the issue that a single invalid field results into valid form in general (since it's skipped, returned explicit `null` and validation resolves).
Need to create a separate issue for that.

Form: Updates state whenever context rules change

---

src/fieldPresets/checkbox.js

setting initialValue for checkbox wasn't working correctly.

Take care about checkbox initialValue
