src/Form.jsx

Covers #71.
* Set `immediate: false` for debounced sync validation
* Decrease the debounce timeout to `250` ms

Form (debouncedValidateField): Set "immediate: false"

---

.eslintrc.js
package-lock.json
package.json
src/Fields/Field.jsx
src/Form.jsx
src/utils/getPropsPatch.js
stories/FullForm.jsx

Resolves the `value` and `initialValue` issue for `Field.Radio` during the registration in the Form.
Related to #38 and #101.
However, I cannot say that this is the best solution.

Form: Register and validate Field.Radio properly

---

src/components/Form.jsx

* `Form.state.submitting` is deprecated and removed from the internal state, as it doesn't affect neither internal logic of Form, nor external usage.

Form: Deprecate "Form.state.submitting"

---

src/components/Form.jsx
stories/ValidationExample.jsx

* Simplifies the composition of `invalidField` List during `Form.validate()` method.
* Stops relying on `nextFields.key().reduce()`

Form (validate): Filter "nextFields" Map instead of reducing it

---

docs/architecture/referencing.md
src/components/createField.jsx
test/unit/components/Field.spec.js

* Implements #194.
* Introduces unit tests for `Field.props.ref` and `Field.props.innerRef`
* Doesn't affect the bundle size

Field: Rename "wrappedRef" to "innerRef". Add unit tests.

---

.eslintrc.js
cypress/scenarios/RxProps/Basic.jsx
cypress/scenarios/RxProps/Delegated.jsx
cypress/scenarios/RxProps/Interdependent.jsx
cypress/scenarios/RxProps/OneTarget.jsx
src/utils/ensafeMap.js
src/utils/fieldUtils/getErrorMessages.js
src/utils/flushFieldRefs.js
src/utils/index.js
src/utils/rxUtils/createSubscriptions.js
src/utils/warning.js
stories/GroupedFields.jsx
stories/ReactiveProps.jsx
stories/RxProps.jsx
test/unit/utils/ensafeMap.spec.js
test/unit/utils/flushFieldRefs.spec.js
test/unit/utils/index.js

Implements alternative interface for reactive props.
* Removes `subscribe` function to operate with fields subscriptions
* Uses recursive proxying to be able to reference fields like `fields.groupName.fieldName.propName`
* Uses safe Map model to ensure unsafe key references do not break the method they are referenced in
* Adapts the existing implementation and tests to work with the introduced changes

RxProps: Uses alternative interface, recursive proxying, safe fields Map

---

.babelrc
.eslintrc.js
.storybook/.babelrc
package-lock.json
package.json
src/classes/Sequence.js
src/utils/fieldUtils/validate.js
src/utils/rxUtils/createSubscriptions.js
src/utils/warning.js
webpack.config.js

Partially refers to #215.
* Removes "babel-polyfill" from babel plugins for the package bundle
* Decreases the bundle size by ~9 Kb (from 93.4 Kb to 84.3 Kb)

Use "regenerator-runtime" instead of "babel-polyfill"

---

.circleci/config.yml
cypress/integration/components/index.js
cypress/integration/field-grouping/index.js
cypress/integration/reactive-props/index.js
cypress/integration/validation/SyncValidation/index.spec.jsx
cypress/plugins/index.js
examples/full/RegistrationForm/RegistrationForm.jsx
examples/reactive-props/SingleTarget.jsx
package.json
src/components/Form.jsx
src/components/createField.jsx
src/utils/fieldUtils/validateAsync.js
src/utils/index.js
src/utils/rxUtils/createRulesSubscriptions.js
src/utils/rxUtils/createSubscriptions.js
src/utils/rxUtils/makeObservable.js

Implements #182.
* `Form.updateField()` method uses a new interface and accepts an `update` parameter, controlling the update of the field record
* All calls to `updateField()` are rewritten to use the new API
* Reduces the size of the library bundle by ~1 Kb
* No breaking changes, API change is purely internal

"updateField" now accepts an "update" function

---

docs/hoc/createField/options.md
src/components/Form.jsx
src/components/createField.jsx
src/fieldPresets/radio.js

Implements #233
* Adds `beforeRegister` method to `createField` options. This method allows to apply additional transformations to `fieldProps` Map right before the field is registered. It also allows to completely prevent the registration when `false` is returned.
* Adds `allowMultiple` flag to `createField` options. When `true` is returned, form allows to register multiple fields with the same name.

Introduces "allowMultiple" and "beforeRegister" options for "createField"

---

cypress/integration/validation/SyncValidation/Form.props.rules.spec.jsx
examples/reactive-props/DelegatedSubscription.jsx
examples/reactive-props/DynamicRequired.jsx
examples/reactive-props/Interdependent.jsx
examples/reactive-props/SingleTarget.jsx
examples/validation/SyncValidation/Form.props.rules.jsx
src/utils/fieldUtils/createPropGetter.js
src/utils/fieldUtils/index.js
src/utils/fieldUtils/validateSync.js
src/utils/flushFieldRefs.js
src/utils/rxUtils/createRulesSubscriptions.js
src/utils/rxUtils/createSubscriptions.js
test/unit/utils/flushFieldRefs.spec.js

Implements #243.
* Removes the usage of `Proxy` completely
* Rewords the API for reactive props, as the consequence
* Introduces explicit helper method to subscribe/get field props in `required` prop and sync rule resolver functions

RxProps: Use alternative API instead of Proxy

---

src/components/Form.jsx
src/utils/fieldUtils/resetField.js

* Fixes #265 
* Adds new `clear` method to the Form class
* Extends `fieldUtils.resetField` function to be a HoF, accepting `getNextValue` function as an argument, and returning an applicator function expecting a `fieldProps` instance.

Adds "Form.clear" for clearing the fields

---

cypress/integration/basics/InitialValues.spec.jsx
cypress/integration/basics/index.js
examples/basics/InitialValues.jsx
examples/fields/Select.jsx
src/components/Form.jsx
src/components/createField.jsx

* Fixes #262 
* Adds `initialValues: PropTypes.object` prop to the `Form` component
* Adjusts the logic to determine field's initial value upon its registration in `createField`
* Uses the following fallback map to get a field's initial value:
* `fieldProps.initialValue`
* `form.props.initialValues[fieldPath]`
* `fieldHocOptions.initialValue`
* Provides integration tests to cover the introduced changes

Accepts "initialValues" prop for "Form" component

---

cypress/integration/basics/Interactions.controlled.spec.jsx
cypress/integration/basics/Interactions.uncontrolled.spec.jsx
cypress/integration/basics/Submit.spec.jsx
cypress/integration/validation/async/index.js
cypress/integration/validation/composite/index.js
cypress/integration/validation/messages/AsyncExtraParam.spec.jsx
cypress/integration/validation/messages/SetErrors.spec.jsx
cypress/integration/validation/sync/Field.props.rule.spec.jsx
examples/full/RegistrationForm/RegistrationForm.jsx
examples/full/RegistrationForm/validation-rules.js
examples/validation/combined/index.jsx
examples/validation/misc/AjaxPrefilling.jsx
src/utils/fieldUtils/createPropGetter.js
src/utils/flushFieldRefs.js
src/utils/flushFieldRefs.test.js
src/utils/formUtils/filterSchemaByField.js
src/utils/formUtils/filterSchemaByField.test.js
src/utils/formUtils/getRulesRefs.js
src/utils/formUtils/mergeRules.js
src/utils/reduceWhile.js
src/utils/reduceWhile.test.js
src/utils/rxUtils/createRulesSubscriptions.js
src/utils/rxUtils/makeObservable.js
src/utils/validation/applyRule.js
src/utils/validation/createRejectedRule.js
src/utils/validation/getFieldRules.js
src/utils/validation/index.js
src/utils/validation/messages/getMessages.test.js
src/utils/validation/messages/getResolvePaths.js
src/utils/validation/validateAsync/applyFieldAsyncRule.js

* Fixes #294 
- Added multiple resolvers support for a single selector in `filterSchemaByField`.
- Simplified `reduceWhile` declaration. Used composition to define derived methods.
- Added unit tests for `reduceWhile`.
- Added unit tests for `filterSchemaByField`.
- Added integration test for multiple resolvers for a single selector.

Handles multiple validation resolvers 

---

.npmignore
examples/fields/BirthDate.jsx
examples/full/RegistrationForm/RegistrationForm.jsx
src/components/Form.jsx
src/components/createField.jsx
src/utils/fieldUtils/serializeFields.js
src/utils/recordUtils.js

Includes temporary fixes and experimental features.
* Partially implements #303
- Adds `serialize` for createField options
- Adds `getInitialValue` for createField options
- Adds `Form.setValues` for direct fields value update (a workaround for #295)

Adds "Form.setValues", "createField.getInitialValue", "createField.serialize"

---

webpack.config.js

webpack: Provides "globalObject" forcing to solve "window" in SSR

---

cypress/integration/basics/Types.spec.js
cypress/integration/basics/UncontrolledFields.spec.js
cypress/integration/basics/index.js
examples/basics/UncontrolledFields.jsx
examples/fields/BirthDate.jsx
examples/index.js
src/components/createField.jsx
src/fieldPresets/input.js
src/utils/formUtils/filterSchemaByField.test.js
src/utils/recordUtils.js
src/utils/recordUtils.test.js
src/utils/reduceWhile.test.js

* Closes #335 
This change is potentially breaking, thus should be released in the next minor version to prevent compatibility issues.

createField: Makes "type" propagation explicit

---

cypress/integration/reactive-props/index.js
examples/reactive-props/DynamicRequired.jsx
src/utils/rxUtils/createPropsSubscriptions.js

* Fixes #344 
- Validation calls originated from reactive subscriptions do not force the validation anymore
- Instead, the subscriber field state is being reset (resetValidityState, resetValidationState), which results into proper predicate passing (i.e. shouldValidateSync).

Stop forcing validation originated from reactive subscription

---

package.json

Windows CLI throws error while running the following npm scripts:
```bash
"cypress": "$(npm bin)/cypress open -e envName=dev",
"cypress:cli": "$(npm bin)/cypress run --spec 'cypress/integration/index.js' --browser chrome",
"test:integration:dev": "$(npm bin)/.bin/cypress run -e envName=dev --spec cypress/integration/index.js --headed --no-exit"
```
```bash
'$' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-advanced-form@1.6.7 cypress: `$(npm bin)/cypress open -e envName=dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-advanced-form@1.6.7 cypress script.
```
Replaced `$(npm bin)` with `node_modules/.bin`

Fix: npm scripts - $(npm bin) wont execute on windows

---

cypress/integration/basics/FirstChange.spec.js
cypress/integration/basics/index.js
examples/basics/FirstChange.jsx
examples/index.js
src/components/Form.jsx

Fix `Form.reset()` so that it resets the dirty state of the form. Implement Storybook example and integration tests for `onFirstChange` callback.

Fix behavior of `onFirstChange` callback with regard to `Form.reset()`

---

package-lock.json
package.json

Moves `bundlesize` package to dev dependencies of the library. Previously it has been added as a save dependency, resulting into being installed for the library's users.
- Fixes #383

Moves "bundlesize" to dev dependency

---

cypress/integration/validation/messages/ValidationMessages.spec.js
examples/validation/messages/ValidationMessages.jsx
src/utils/validation/messages/getMessages.js
src/utils/validation/messages/getMessages.test.js

- Adds missing `[valuePropName]` key in the message resolver arguments
- Adjusts integration test scenario to use a dynamic "value" property in the error message
- Adjusts integration tests to reflect the usage of dynamic "value" property in the error message
- Fixes #387

Sets [valuePropName] key on message resolver arguments
